### PR TITLE
Add loglevel and logfilename to support logging to file

### PR DESCRIPTION
**Pull request by tux75at**
For the project, where i want to use this code, it is important to log into a log file.
The logging library supports logging to files and also loglevels, added parameters and commands to support this function.
There should be no side effects for existing projects, unused parameters should behave as before.

### CODE REVIEW

**Comment by bdr99** [comment]
Thanks for the contribution! I checked out your branch and tried initializing a client like this:
```python
client = pymazda.Client("myemail", "mypassword", "MNAO", logginglevel="DEBUG", logfilename="test.log")
```
And then ran some commands to interact with the API:
```python
vehicles = await client.get_vehicles()
print(vehicles)
for vehicle in vehicles:
    print(vehicle)
    status = await client.get_vehicle_status(vehicle["id"])
```
But when I run it, no log file is created. Even if I create `test.log` manually, nothing is added to it. Is it working for you?

**Comment by bdr99** [comment]
Never mind, disregard the above comment. There was an issue with my test script.

**Comment by bdr99** [comment]
Thanks for the contribution! However I'm not sure that this is the way the logging library is meant to be used. You should be able to just add this in the project where you are using pymazda:
```python3
logging.basicConfig(filename="debug.log", level=logging.DEBUG)
```
And then it should just log to file without any changes needed to pymazda. I tested this and it works for me. Can you let me know if this works for your use case?

**Comment by tux75at** [comment]
First time i used logging and did not fully understand.

One change which i would prepair is the logging level. Should be able to be set with your approach, but the log entries are all set to debug, these should use different levels.
`self.logger.warning("Server reports access token was expired. Retrieving new access token.")`
`self.logger.info(f"Sending {method} request to {uri}{retry_message}")`
I think its only the file "connection.py"

**Comment by tux75at** [comment]
Removed setting for loglevel and logfile, this shall be set somewhere else.
The changed log level for the log messages is still usefull to prevent overflowing log files.

**Comment by bdr99** [comment]
It looks like you actually _increased_ the log level of many of the log messages. How would that prevent overflowing log files? Wouldn't it actually make more messages get logged?

**Comment by tux75at** [comment]
I changed the loglevel at the generation of the messages, as all logs were at DEBUG. At the moment all log messages can be activated or deactivated by setting the loglevel to DEBUG.
For normal operation the loglevel setting should be set to ERROR or possibly if someone wants to see more to WARNING.
That way all the INFO messages are filtered and not written to the log file. But this requires a loglevel at the generation of the message which is set differently depending on the message.
Yes, it was increased, but now it can be filtered. If no logging is wanted (specially to file) then the setting of basicConfig can be removed (set in the project).

**Comment by bdr99** [comment]
Hi @tux75at, sorry for the long delay. I've been quite busy lately and haven't had a lot of time to think about pymazda.

I see what you mean about the log levels, and I'm fine with making them more granular. However I would like to request a couple of changes. I would be happy to merge this PR if you make these changes.

- Please change lines 175, 179, 187, and 259 to info. Those log messages are completely normal and expected during regular usage of this library, so they should not be warnings.
- Please change lines 170 and 236 back to debug. I think the only reason someone would ever need to view the raw request and response payloads is if they were working on developing this library.

**Comment by bdr99** [comment]
Thanks for making those changes!

**Pull request merged**
